// <auto-generated />
namespace Salon.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class add_in_carmodel : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(add_in_carmodel));
        
        string IMigrationMetadata.Id
        {
            get { return "202309141823261_add_in_carmodel"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
